server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: libro
          uri: http://localhost:8081
          predicates:
            - Path=/libros/**
        - id: autor
          uri: http://localhost:8082
          predicates:
            - Path=/autores/**
